### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by olivierdalang** [mojodna/marblecutter-virtual#16]
Currently, docker build fails with :
```
Step 17/20 : RUN pip install -U numpy && pip install -r requirements-server.txt && rm -rf /root/.cache
---> Running in de7667b98403
Collecting numpy
Downloading https://files.pythonhosted.org/packages/40/de/0ea5092b8bfd2e3aa6fdbb2e499a9f9adf810992884d414defc1573dca3f/numpy-1.18.1.zip (5.4MB)
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-N0QYrg/numpy/setup.py", line 32, in <module>
raise RuntimeError("Python version >= 3.5 required.")
RuntimeError: Python version >= 3.5 required.
----------------------------------------
[91mCommand "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-N0QYrg/numpy/
[0m
[91mYou are using pip version 8.1.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[0m
Removing intermediate container de7667b98403
The command '/bin/sh -c pip install -U numpy && pip install -r requirements-server.txt && rm -rf /root/.cache' returned a non-zero code: 1
```

**Comment by j08lue** [comment]
You should probably use `python3` and also remember to `python3 -m pip install --upgrade pip`.

**Comment by olivierdalang** [comment]
Yes it's linked to some deps not supporting python2 anymore. But we could also pin those deps, which would be less work...

**Comment by sethfitz** [comment]
Before I disappeared into the ether, I was using marblecutter with both python 2 and 3. It sounds like it's time to discontinue python 2 support and update dependencies and scripts as appropriate. I would happy accept a PR for this (I don't have time to do it myself).

**Comment by adrienDog** [comment]
Hello, I see there is  potential fix for this issue https://github.com/mojodna/marblecutter-virtual/pull/18/files can it be merged?
