### ISSUE TITLE
Issue with current docker-compose

### ISSUE THREAD

**Issue by bmulcahy** [mojodna/marblecutter-virtual#9]
When building the latest docker container in the docker compose file I receive this error

```bash

Attaching to marblecuttervirtual_marblecutter_1
marblecutter_1  | Traceback (most recent call last):
marblecutter_1  |   File "server.py", line 7, in <module>
marblecutter_1  |     from virtual.web import app
marblecutter_1  |   File "/opt/marblecutter/virtual/web.py", line 9, in <module>
marblecutter_1  |     from marblecutter import NoCatalogAvailable, tiling
marblecutter_1  |   File "/usr/local/lib/python2.7/dist-packages/marblecutter/__                 init__.py", line 12, in <module>
marblecutter_1  |     import rasterio
marblecutter_1  |   File "/usr/local/lib/python2.7/dist-packages/rasterio/__init                 __.py", line 22, in <module>
marblecutter_1  |     from rasterio._base import gdal_version
marblecutter_1  |   File "rasterio/_base.pyx", line 20, in init rasterio._base
marblecutter_1  |   File "/usr/local/lib/python2.7/dist-packages/rasterio/compat                 .py", line 26, in <module>
marblecutter_1  |     import mock
marblecutter_1  | ImportError: No module named mock
marblecuttervirtual_marblecutter_1 exited with code 1


```

**Comment by sethfitz** [comment]
Thanks for spotting this.

I just pushed a change that addresses this. The underlying issue is https://github.com/mapbox/rasterio/issues/165

(It's not a problem when deploying to AWS, as that uses the Python 3 runtime, which includes `mock` as part of the built-in `unittest` module.)

**Comment by sethfitz** [comment]
Correction: https://github.com/mapbox/rasterio/issues/1651
